version: '3'
volumes:
  node_modules:
services:
  hara_watcher:
    image: hara:scan
    environment:
      - PRIV_NETWORK=http://192.168.99.100:8546
      - DB_ENDPOINT=http://192.168.99.100:8000
      - IS_DEV=true
    command: bash -c "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/var/task
      - node_modules:/var/task/node_modules
  
