service: hara-scan # NOTE: update this with your service name

custom:
  webpackIncludeModules:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  # serverless-offline:
  #   babelOptions:
  #     presets: ["es2015"]

plugins:
  - serverless-offline
  - serverless-offline-scheduler
  - serverless-webpack

frameworkVersion: "<=1.28.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:REGION}
  stage: ${opt:stage, 'dev'}
  role: ${env:ROLE}
  tags:
    Namespace: hara-scan
    # change the [service-name]
    Name: hara-scan-${self:provider.stage}
    Stage: ${self:provider.stage}
  # tags for all stacks generate by serverless, exp dynamodb, cloudwatch, etc
  # same with lambda tags
  stackTags:
    Namespace: hara-scan
    # change the [service-name]
    Name: hara-scan-${self:provider.stage}
    Stage: ${self:provider.stage}
  environment:
    PRIV_NETWORK: ${env:PRIV_NETWORK}
    IS_DEV: ${env:IS_DEV}
    TB_HARA_BLOCK: ${env:TB_HARA_BLOCK}_${self:provider.stage}
    REGION: ${env:REGION}

package:
  exclude:
    - node_modules/dynamodb-localhost/**
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**
    - tests/**

functions:
  get_transactions:
    handler: handler._getTransactions
    timeout: 10
    events:
    - http:
        path: get_transactions
        method: get
  
  get_transactions_by_address:
    handler: handler._getTransactionsByAddress
    timeout: 10
    events:
    - http:
        path: get_transactions_by_address
        method: get

  get_verified_contracts:
    handler: handler._getVerifiedContracts
    timeout: 10
    events:
    - http:
        path: get_verified_contracts
        method: get

  get_blocks:
    handler: handler._getBlocks
    timeout: 10
    events:
    - http:
        path: get_blocks
        method: get
  
  get_detail_transaction:
    handler: handler._getDetailTransaction
    timeout: 10
    events:
    - http:
        path: get_detail_transaction
        method: get

  get_alias_functions:
    handler: handler._getWeb3Functions
    timeout: 60
    events:
    - http:
        path: get_alias_functions
        method: get
  
  get_total_transaction:
    handler: handler._getTotalTransaction
    timeout: 10
    events:
    - http:
        path: get_total_transaction
        method: get

resources:
  Resources:    
    haraBlock:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: hash
            AttributeType: S
          - AttributeName: from
            AttributeType: S
          - AttributeName: to
            AttributeType: S
          - AttributeName: contractAddress
            AttributeType: S
          - AttributeName: number
            AttributeType: N
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: hash
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: type_from
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: from
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: type_to
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: to
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: type_contractAddress
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: contractAddress
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: type_blocknumber
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: number
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: hara_block_${self:provider.stage}
