service: hara-watcher # NOTE: update this with your service name

custom:
  serverless-offline:
    babelOptions:
      presets: ["es2015"]
  webpackIncludeModules:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'

plugins:
  - serverless-offline
  - serverless-offline-scheduler
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: local
  stage: ${opt:stage, 'dev'}
  environment:
    PRIV_NETWORK: ${env:PRIV_NETWORK}
    DB_ENDPOINT: ${env:DB_ENDPOINT}
    IS_DEV: true

package:
  exclude:
    - node_modules/dynamodb-localhost/**
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**
    - tests/**

functions:
  get_transactions:
    handler: handler._getTransactions
    timeout: 10
    events:
    - http:
        path: get_transactions
        method: get

  get_blocks:
    handler: handler._getBlocks
    timeout: 10
    events:
    - http:
        path: get_blocks
        method: get
  
  get_detail_transaction:
    handler: handler._getDetailTransaction
    timeout: 10
    events:
    - http:
        path: get_detail_transaction
        method: get
